### PR TITLE
262177: Restructure services files

### PR DESCRIPTION
**Pull request by ppotturi**
# **What this PR does / why we need it**:
Restructured services files. 

# **Special notes for your reviewer**
*Any specific actions or notes on review?*

# Testing
*Any relevant testing information and pipeline runs.*

# Checklist (please delete before completing or setting auto-complete)
- [x] Story Work items associated (not Tasks)
- [ ] Successful testing run(s) link provided
- [x] Title pattern should be `{work item number}: {title}`
- [ ] Description covers all the changes in the PR
- [ ] This PR contains documentation
- [ ] This PR contains tests

# **How does this PR make you feel**:
gif

### CODE REVIEW

**Comment by ppotturi** [comment]
SoExcited~GIF

**Review by jeevankuduvaravindran — APPROVED** [review]
ThisIsAllTooMuchGIF

**Review by jeevankuduvaravindran — APPROVED** [review]
WowAgainColinJostGIF

**Comment by ganeshg2491** [comment]
DinnerTimeKittenGIF

**Review by jeevankuduvaravindran — APPROVED** [review]
AreYouSureAboutThatTheRockGIF (2)

**Comment by ppotturi** [comment]
> AreYouSureAboutThatTheRockGIF (2) [ AreYouSureAboutThatTheRockGIF (2) ](https://user-images.githubusercontent.com/119388966/283576575-6e66bcad-62be-46f5-bbd5-77adf09a0fd1.gif) [ ](https://user-images.githubusercontent.com/119388966/283576575-6e66bcad-62be-46f5-bbd5-77adf09a0fd1.gif)

YES.................

**Review by DaRoszko — APPROVED** [review]

**Pull request merged**
